### PR TITLE
Implement Namibia spray form

### PR DESCRIPTION
**Pull request by githengi**
PR for [https://github.com/OpenSRP/opensrp-client-reveal/issues/108](https://github.com/OpenSRP/opensrp-client-reveal/issues/108)

This PR is based on [https://github.com/OpenSRP/opensrp-client-reveal/releases/tag/V1.4.0](https://github.com/OpenSRP/opensrp-client-reveal/releases/tag/V1.4.0) # which is used for field testing

Depends on 
 - [https://github.com/OpenSRP/opensrp-client-core/pull/189](https://github.com/OpenSRP/opensrp-client-core/pull/189)

 - [https://github.com/OpenSRP/opensrp-client-native-form/pull/148](https://github.com/OpenSRP/opensrp-client-native-form/pull/148)

### CODE REVIEW

**Comment by vincent-karuri** [comment]
Some issues found (may not be exhaustive):

`Type of Structure` field is not in data dictionary, should it be in the form?

`# of sprayable structures` not displayed when form_data.any_sprayed=="YES"

`# of unsprayable structures` not displayed when  form_data.any_sprayed=="YES"

comment edit text (`form_data.refusal_reasons_for_not_spraying_Comment`) for reason refused is not appearing 

Reason for refusal (`form_data.refusal_reasons_for_not_spraying`) not disappearing after switching to `form_data.any_sprayed` "Yes" when previously it was "No"

`form_data.house_population, form_data.total_population_sprayedrooms, form_data.name_household, form_data.health_number, form_data.confirm` :  none of these fields appear on `if form_data.any_sprayed=="Yes"`

**Comment by githengi** [comment]
> Type of Structure field is not in data dictionary, should it be in the form?
This the field in data dictionary location.properties.type

**Comment by vincent-karuri** [comment]
Add a red asterisk to `Were any structures sprayed?`

**Comment by githengi** [comment]
Fixed the issues identified

**Comment by vincent-karuri** [comment]
image


Samsung J5, red asterisk is not visible on the `Were any structures sprayed`?

**Comment by githengi** [comment]
> Samsung J5, red asterisk is not visible on the `Were any structures sprayed`?

This is a bug on Native forms. I have removed the question mark to overcome the bug. I have also created an Issue on Native forms to track the bug [https://github.com/OpenSRP/opensrp-client-native-form/issues/154](https://github.com/OpenSRP/opensrp-client-native-form/issues/154)

**Pull request merged**
