### PR TITLE
Implement Botswana IRS Form

### PR DESCRIPTION
**Pull request by githengi**
PR for [https://github.com/OpenSRP/opensrp-client-reveal/issues/109](https://github.com/OpenSRP/opensrp-client-reveal/issues/109)

Depends on [https://github.com/OpenSRP/opensrp-client-native-form/pull/150](https://github.com/OpenSRP/opensrp-client-native-form/pull/150)

### CODE REVIEW

**Comment by vincent-karuri** [comment]
Is there a reason why the fields that have cumulative totals cannot be derived from their individual components e.g. number of rooms sprayed derived from total of number of rooms sprayed with different drugs?

Instead of adding extra validators to the individual components, which I guess would have to be added to each of the individual components and not just one?

**Comment by githengi** [comment]
@craigappl Kindly respond to the above queries. 

@vincent-karuri Kindly not i have used the fields as on the reveal data dictionary

**Comment by craigappl** [comment]
@vincent-karuri and @githengi , I agree that it's inefficient and the suggested way is much better. This is for a demo application. The forms were sent over to us as defined in the data dictionary and we are not in a position to change the logic that was share from the customer.

**Comment by vincent-karuri** [comment]
Why do we have logic and forms on Namibia in this pr?

**Comment by vincent-karuri** [comment]
Issues found (may not be exhaustive):

Seems like no validation for total number of sprayable modern and traditional rooms < number rooms sprayable.
Seems like no validation for total number of sprayed modern and traditional rooms < number rooms sprayed.
Don't see this field `number_sprayed_other_partial_spray`.
Not validating `number_of_rooms_not_sprayed` < `number_of_rooms`

**Comment by githengi** [comment]
> Seems like no validation for total number of sprayable modern and traditional rooms < number rooms sprayable.
> Seems like no validation for total number of sprayed modern and traditional rooms < number rooms sprayed.

These are not required or defined in the data dictionary

**Comment by githengi** [comment]
> Don't see this field `number_sprayed_other_partial_spray`.

This is shown if Its **First Visit** and `How many other structures are in this home? (Other structures such as toilets and corridors)` is greater than 0
image

**Comment by githengi** [comment]
> Not validating `number_of_rooms_not_sprayed` < `number_of_rooms`

Fixed

**Comment by vincent-karuri** [comment]
> > Seems like no validation for total number of sprayable modern and traditional rooms < number rooms sprayable.
> > Seems like no validation for total number of sprayed modern and traditional rooms < number rooms sprayed.
> 
> These are not required or defined in the data dictionary

The validation calculation define for these is similar to the one used in 
`n_people_homestead_underage5` and `n_people_homestead_overage5, where you defined the cumulative total validator. This was also not explicitly declared in the data dicitonary.

Unless there is some kind of selective validation?

**Comment by vincent-karuri** [comment]
> > Don't see this field `number_sprayed_other_partial_spray`.
> 
> This is shown if Its **First Visit** and `How many other structures are in this home? (Other structures such as toilets and corridors)` is greater than 0
> image

As per the data dictionary, there is only one constraint `if number_other_structures>0`.

**Comment by githengi** [comment]
> As per the data dictionary, there is only one constraint `if number_other_structures>0`.

This is true however `number_other_structures` has a constraint `if visit == 'First visit"`

**Comment by githengi** [comment]
> The validation calculation define for these is similar to the one used in
> `n_people_homestead_underage5` and `n_people_homestead_overage5`, where you defined the cumulative total validator. This was also not explicitly declared/required in the data dictionary.

There are defined in the data dictionary

`Add data check with ddt + actellic + lamba == number_sprayed`

`if n_people_homestead>1, Add a data check that <5 + >5 == total`

**Comment by vincent-karuri** [comment]
> > The validation calculation define for these is similar to the one used in
> > `n_people_homestead_underage5` and `n_people_homestead_overage5`, where you defined the cumulative total validator. This was also not explicitly declared/required in the data dictionary.
> 
> There are defined in the data dictionary
> 
> `Add data check with ddt + actellic + lamba == number_sprayed`
> 
> `if n_people_homestead>1, Add a data check that <5 + >5 == total`

Okay

**Comment by vincent-karuri** [comment]
> > Not validating `number_of_rooms_not_sprayed` < `number_of_rooms`
> 
> Fixed

This is still not fixed.

**Comment by vincent-karuri** [comment]
> > As per the data dictionary, there is only one constraint `if number_other_structures>0`.
> 
> This is true however `number_other_structures` has a constraint `if visit == 'First visit"`

This still doesn't show, even with `First visit` selected and `number_other_structures>0`.

**Comment by vincent-karuri** [comment]
Do these fields show: `number_sprayed_traditional_partial_spray` and 
`number_sprayed_modern_partial_spray`?

Please run through all logic you think may be affected by a change you make when testing.

**Comment by githengi** [comment]
> Do these fields show: `number_sprayed_traditional_partial_spray` and
> `number_sprayed_modern_partial_spray`?
> 
> Please run through all logic you think may be affected by a change you make when testing.

I verified this logic and its working if the below constraints are met as defined in data dictionary
`number_sprayed_traditional_partial_spray`  shows if `number_rooms_traditional > 0`
`number_sprayed_modern_partial_spray` shows if `number_rooms_modern > 0`

**Pull request merged**
